# Generated by Django 2.2.10 on 2020-05-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
    ]
