# Generated by Django 2.2.10 on 2020-05-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Description is not provided for this product!'),
            preserve_default=False,
        ),
    ]
