# Generated by Django 2.2.10 on 2020-05-26 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200526_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='refund_requestedordered',
            new_name='refund_requested',
        ),
    ]
